remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Yangfei Dai
description: Welcome to my homepage! I am master student at the University of Illinois at Urbana-champaign. My advisor is [Timothy Bretl](http://bretl.csl.illinois.edu/people). I'm interested in machine learning and computer vision algorithms. This is a collection of my previous projects
